export const LOAD_URL_SUCCESS = 'LOAD_URL_SUCCESS';
export const LOAD_URL_FAILURE = 'LOAD_URL_FAILURE';

export const LOAD_LANG_SUCCESS = 'LOAD_LANG_SUCCESS';
export const LOAD_LANG_FAILURE = 'LOAD_LANG_FAILURE';
export const LOAD_LANGUAGES_SUCCESS = 'LOAD_LANGUAGES_SUCCESS';

export const SWITCH_LANGUAGE = 'SWITCH_LANGUAGE';
